// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1x_7yG8DjSHYDhymFSrumzlItYur8Ryc',
    appId: '1:816467344174:web:a9238e33531c38e7aad8bf',
    messagingSenderId: '816467344174',
    projectId: 'cat-feeder-hjh',
    authDomain: 'cat-feeder-hjh.firebaseapp.com',
    storageBucket: 'cat-feeder-hjh.firebasestorage.app',
    measurementId: 'G-Q9PEVTSMEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPCkF_zKtoNn_fKJ9Vj_cNThlBgUt96MY',
    appId: '1:816467344174:android:2780516218da119eaad8bf',
    messagingSenderId: '816467344174',
    projectId: 'cat-feeder-hjh',
    storageBucket: 'cat-feeder-hjh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8jsDwzzLGJmAny-U1AfYPNEe6GE13Dek',
    appId: '1:816467344174:ios:9b5be69b128d2764aad8bf',
    messagingSenderId: '816467344174',
    projectId: 'cat-feeder-hjh',
    storageBucket: 'cat-feeder-hjh.firebasestorage.app',
    iosBundleId: 'com.example.catFeederApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8jsDwzzLGJmAny-U1AfYPNEe6GE13Dek',
    appId: '1:816467344174:ios:9b5be69b128d2764aad8bf',
    messagingSenderId: '816467344174',
    projectId: 'cat-feeder-hjh',
    storageBucket: 'cat-feeder-hjh.firebasestorage.app',
    iosBundleId: 'com.example.catFeederApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1x_7yG8DjSHYDhymFSrumzlItYur8Ryc',
    appId: '1:816467344174:web:c7df0426ab30aa32aad8bf',
    messagingSenderId: '816467344174',
    projectId: 'cat-feeder-hjh',
    authDomain: 'cat-feeder-hjh.firebaseapp.com',
    storageBucket: 'cat-feeder-hjh.firebasestorage.app',
    measurementId: 'G-2M5VXESBNT',
  );
}
