name: cat_feeder_app
description: AI-Powered Automated Cat Feeder System

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  firebase_core: ^4.10.0
  cloud_firestore: ^6.5.0
  firebase_messaging: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true